-- AlterTable
ALTER TABLE "Group" ADD COLUMN     "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "GroupMember" ADD COLUMN     "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "moduleActivity" JSONB NOT NULL DEFAULT '{}';

-- AlterTable
ALTER TABLE "PlanMember" ADD COLUMN     "moduleSeen" JSONB NOT NULL DEFAULT '{}';
